import re

with open("V1_raw.sql", "r", encoding="utf-8") as f:
    content = f.read()

# Remove pg_dump boilerplate
lines = content.split('\n')
cleaned = []
skip_block = False

for line in lines:
    # Skip pg_dump headers
    if line.strip().startswith('\\restrict') or line.strip().startswith('\\unrestrict'):
        continue
    if line.strip().startswith('--') and ('Dumped from' in line or 'Dumped by' in line):
        continue
    if line.strip().startswith('SET ') or line.strip().startswith('SELECT pg_catalog'):
        continue
    if line.strip() == '':
        continue
    # Skip SEQUENCE stuff (BIGSERIAL auto-creates sequences)
    if 'CREATE SEQUENCE' in line:
        skip_block = True
        continue
    if 'ALTER SEQUENCE' in line:
        skip_block = True
        continue
    if skip_block and line.strip() == ');':
        skip_block = False
        continue
    if skip_block:
        continue
    # Skip OWNED BY
    if 'ALTER SEQUENCE' in line or 'OWNED BY' in line:
        continue
    # Remove schema prefix
    line = line.replace('public.', '')
    # Convert comment markers
    line = line.replace('-- Name:', '--')
    line = line.replace('; Type: TABLE', '')
    line = line.replace('; Schema:', '')
    line = line.replace('; Owner:', '')
    cleaned.append(line)

result = '\n'.join(cleaned)

# Clean up multiple blank lines
while '\n\n\n\n' in result:
    result = result.replace('\n\n\n\n', '\n\n\n')
while '\n\n\n' in result:
    result = result.replace('\n\n\n', '\n\n')

# Add header
header = """-- ============================================================
-- V1__init_schema.sql
-- AI Commerce Platform - Generated by Hibernate via pg_dump
-- ============================================================

"""
with open("V1__init_schema.sql", "w", encoding="utf-8") as f:
    f.write(header + result)

print("CLEANED OK")