$input = Get-Content "V1__init_schema.sql" -Encoding UTF8
$lines = @()
$skip = $false
foreach ($line in $input) {
    if ($line -match '^SET ' -or 
        $line -match '^SELECT pg_catalog' -or
        $line -match '^CREATE SEQUENCE' -or
        $line -match '^ALTER SEQUENCE' -or
        $line -match '^\\restrict' -or
        $line -match '^\\unrestrict' -or
        $line -match '^-- Name:' -or
        $line -match '^-- Dumped' -or
        $line -match '^-- PostgreSQL') {
        continue
    }
    if ($line.Trim() -eq '') { continue }
    if ($line -match '^ALTER TABLE ONLY ') { continue }
    if ($line -match 'ADD CONSTRAINT (fk|uk|pk)') { continue }
    $line = $line -replace 'public\.', ''
    $line = $line -replace '::.*?[,)]', ','
    $line = $line -replace '::.*$', ''
    $line = $line -replace '  +', ' '
    $lines += $line
}
$header = @"
-- ============================================================
-- V1__init_schema.sql
-- AI Commerce Platform - Auto-generated by Hibernate + pg_dump
-- All tables, indexes, and constraints
-- ============================================================

"@
$header + ($lines -join "`n") | Set-Content "V1_cleaned.sql" -Encoding UTF8
Write-Output "DONE"